# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.srcs/sources_1/ip/PLL/PLL.xci
# IP: The module: 'PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.gen/sources_1/ip/PLL/PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.gen/sources_1/ip/PLL/PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.gen/sources_1/ip/PLL/PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.srcs/sources_1/ip/PLL/PLL.xci
# IP: The module: 'PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.gen/sources_1/ip/PLL/PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.gen/sources_1/ip/PLL/PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/huawei/Documents/GitHub/CPU_Learning/myCPU/rv32icpu.gen/sources_1/ip/PLL/PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
